[dev]
  command = "yarn dev"

[build]
  command = "yarn generate"
  publish = "dist/"
  functions = "functions/"


# [[redirects]]
#   from = "api/*"
#   to = ".netlify/functions/:splat"

# [[redirects]]
#   from = "/conference/*"
#   to = "/:splat"
