backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  use_large_media_transforms_in_media_library: false
local_backend: true
publish_mode: editorial_workflow
display_url: http://www.torphinsplaygroup.co.uk
# show_preview_links: false
#logo_url: https://mctweb.co.uk/_nuxt/img/95f0951.svg
media_folder: 'static/uploads' # Media files will be stored in the repo under static/images/uploads
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
editor: 
  preview: false
collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    label_singular: 'Page'
    folder: 'content/pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Page Title, name: title, widget: string, required: true }
      - { label: Meta Description, name: brief, widget: string, required: true, hint: "This is displayed on google search results" }
      - { label: Meta Image, name: metaimage, widget: image, required: false }
      - widget: 'list'
        name: 'section'
        label: 'Section'
        types: 
          - label: 'General Section'
            name: 'general-section'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: markdown, required: false, buttons: ['bold'], minimal: true}
              - { label: Body, name: body, widget: markdown, required: false,  buttons: ['bold', 'italic', 'link'], editor_components: ['image']}
              - { label: Image, name: image, widget: image, required: false }
              - { name: flip, label: "Flip", widget: boolean, default: true, required: false }
              - widget: 'list'
                name: 'buttons'
                label: 'Buttons'
                fields:
                - { label: Text, name: text, widget: string, }
                - label: "Internal Page"
                  name: "page"
                  widget: "relation"
                  collection: "pages"
                  search_fields: ["title"]
                  value_field: "title"
                  required: false
                  display_fields: ["title", "slug"]
                - { label: (Or External Url), name: url, required: false, widget: string, }
                - { label: Specific Title, name: uid, widget: string, required: false }

          - label: 'Header'
            name: 'header'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: markdown, required: false, buttons: ['bold'], minimal: true}
              - { label: Body, name: body, widget: markdown, required: false,  buttons: ['bold', 'italic', 'link'], editor_components: ['image']}
              - { label: Image, name: image, widget: image, required: false }
              - { name: flip, label: "Flip", widget: "boolean", default: true, required: false }
              - widget: 'list'
                name: 'buttons'
                label: 'Buttons'
                fields:
                - { label: Text, name: text, widget: string }
                - label: "Internal Page"
                  name: "page"
                  widget: "relation"
                  collection: "pages"
                  search_fields: ["title"]
                  required: false
                  value_field: "title"
                  display_fields: ["title", "slug"]
                - { label: (Or External Url), name: url, widget: string,required: false, }
                - { label: Specific Title, name: uid, widget: string }
                
          - label: 'Standout'
            name: 'standout'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: markdown, required: false, buttons: ['bold'], minimal: true}
              - { label: Body, name: body, widget: markdown, required: false,  buttons: ['bold', 'italic', 'link'], editor_components: ['image']}
              - { name: flip, label: "Flip", widget: "boolean", default: true, required: false }
              - widget: 'list'
                name: 'buttons'
                label: 'Buttons'
                fields:
                - { label: Text, name: text, widget: string }
                - label: "Internal Page"
                  name: "page"
                  widget: "relation"
                  collection: "pages"
                  search_fields: ["title"]
                  value_field: "title"
                  required: false
                  display_fields: ["title", "slug"]
                - { label: (Or External Url), name: url, widget: string, required: false,}
                - { label: Specific Title, name: uid, widget: string, required: false }

          - label: 'Meet The Team'
            name: 'meet-the-team'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - widget: 'list'
                name: 'team'
                label: 'Team Member'
                fields:
                - { label: Name, name: name, widget: string, required: false }
                - { label: Image, name: image, widget: image, required: false  }
                - { label: Description, name: description, widget: markdown, required: false, buttons: ['bold', 'italic']}
                - { label: Biography File, name: download, widget: file, required: false, choose_url: false  }

          - label: 'Gallery'
            name: 'gallery'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - widget: 'list'
                name: 'images'
                label: 'Images'
                fields:
                - { label: Name, name: name, widget: string, required: false }
                - { label: Image, name: image, widget: image, required: false  }

          - label: 'File Download'
            name: 'file-download'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: markdown, required: false, buttons: ['bold'], minimal: true}
              - { label: Body, name: body, widget: markdown, required: false,  buttons: ['bold', 'italic', 'link'], editor_components: ['image']}
              - { name: flip, label: "Flip", widget: "boolean", default: true, required: false }
              - { name: file, label: "File", widget: "file", required: false }
              - { label: "Button Text", name: button, widget: string, required: false}

          - label: 'File Download List'
            name: 'file-download-list'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - widget: 'list'
                name: 'downloads'
                label: 'Downloads'
                fields:
                  - { label: Title, name: title, widget: markdown, required: false, buttons: ['bold'], minimal: true}
                  - { name: file, label: "File", widget: "file", required: false }
                  - { name: url, label: "Web Address", widget: "string", required: false }

          - label: 'List'
            name: 'list-section'
            widget: object
            summary: '{{fields.title}}'
            fields:
              - widget: 'list'
                name: 'list'
                label: 'List'
                fields:
                - { label: Title, name: title, widget: string, required: false }
                - { label: Body, name: body, widget: markdown, required: false,  buttons: ['bold', 'italic', 'link'], editor_components: ['image']}

  - name: 'news' # Used in routes, e.g., /admin/collections/blog
    label: 'Articles' # Used in the UI
    folder: 'content/news' # The path to the folder where the documents are stored
    preview_path: '/news/{{slug}}'
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: Title, name: title, widget: string, required: true }
      - {
          label: Small Description,
          name: description,
          widget: text,
          required: true,
          hint: 'This is displayed on google search results and on blog cards'
        }
      - {
          label: Blog Post,
          name: body,
          widget: 'markdown',
          buttons: ['bold', 'italic', 'link']
        }


  - name: 'settings' 
    label: 'Settings' 
    files: 
      - label: 'Navigation'
        name: 'navigation'
        file: 'content/settings/navigation.md'
        fields:
          - widget: 'list'
            name: 'links'
            label: 'Links'
            fields:
            - { label: Text, name: text, widget: string }
            - label: "Internal Page"
              name: "page"
              widget: "relation"
              collection: "pages"
              search_fields: ["title"]
              value_field: "title"
              display_fields: ["title", "slug"]

      - label: 'Footer'
        name: 'footer'
        file: 'content/settings/footer.md'
        fields:
          - { label: Footer Text, name: footertext, widget: 'markdown', buttons: ['bold', 'italic', 'link'], }
          - widget: 'list'
            name: 'links'
            label: 'Links'
            fields:
            - { label: Text, name: text, widget: string }
            - label: "Internal Page"
              required: false
              name: "page"
              widget: "relation"
              collection: "pages"
              search_fields: ["title"]
              value_field: "title"
              display_fields: ["title", "slug"]
            - { label: (Or External Url), name: url, widget: string,required: false, }
            - { label: Specific Title, name: id, widget: string,required: false }
