backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  use_large_media_transforms_in_media_library: false
local_backend: true
publish_mode: editorial_workflow
#logo_url: https://mctweb.co.uk/_nuxt/img/95f0951.svg
media_folder: 'assets/uploads' # Media files will be stored in the repo under static/images/uploads
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'
